"use client";
import {useCallback,useEffect,useId,useRef,useState} from "react";
import {ArrowRight,Check,Clock3,Clover,Copy,MessageCircle,RefreshCw,Send,ShieldCheck,Sparkles,Wallet,X} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {toast} from "sonner";
import {DEMO_WALLETS,DrawResult,DrawState,demoState,demoViewerOutcome,ROUND_MS} from "@/lib/draw";

const colors=["violet","mint","rose","blue","peach","yellow","violet","mint"];
export function Avatar({index=0,small=false}:{index?:number;small?:boolean}){return <span className={`wallet-avatar ${colors[index%8]} ${small?"small":""}`}><span className={`pixel-face face-${index%4}`}><i/><i/><b/></span></span>;}
export function Solana({size=20}:{size?:number}){const gradient=useId();return <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true"><defs><linearGradient id={gradient} x1="100%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stopColor="#00FFA3"/><stop offset="100%" stopColor="#DC1FFF"/></linearGradient></defs><path fill={`url(#${gradient})`} d="M5 4h17l-4 4H1zm-4 6h17l4 4H5zm4 6h17l-4 4H1z"/></svg>;}
export const short=(value:string)=>value.length>14?`${value.slice(0,4)}…${value.slice(-4)}`:value;

export function useDraw(){
 const [state,setState]=useState<DrawState|null>(null);const [online,setOnline]=useState(true);const offset=useRef(0);
 useEffect(()=>{let alive=true;const tick=()=>setState(demoState(Date.now()+offset.current));const sync=async()=>{try{const response=await fetch("/api/draw");if(!response.ok)throw new Error();const next=await response.json() as DrawState;if(alive){offset.current=next.serverTime-Date.now();setState(next);setOnline(true);}}catch{if(alive)setOnline(false);}};tick();void sync();const timer=setInterval(tick,250);const syncTimer=setInterval(sync,30000);const visible=()=>{if(!document.hidden)void sync();};document.addEventListener("visibilitychange",visible);return()=>{alive=false;clearInterval(timer);clearInterval(syncTimer);document.removeEventListener("visibilitychange",visible);};},[]);
 return {state,online,seconds:state?Math.max(0,Math.ceil((state.endAt-state.serverTime)/1000)):180};
}

export function Chat({open,onClose}:{open:boolean;onClose:()=>void}){
 const [messages,setMessages]=useState<Array<{id:number;nickname:string;body:string;createdAt:number}>>([]);const [body,setBody]=useState("");const [nickname,setNickname]=useState("");const [error,setError]=useState("");const [ready,setReady]=useState(false);const [sending,setSending]=useState(false);const bottom=useRef<HTMLDivElement>(null);const oldCount=useRef(0);
 const refresh=useCallback(async()=>{try{const r=await fetch("/api/chat");const data=await r.json() as {messages:typeof messages;nickname:string;error?:string};if(!r.ok)throw new Error(data.error);setMessages(data.messages);setNickname(data.nickname);setError("");setReady(true);}catch(e){setError(e instanceof Error?e.message:"Chat is reconnecting.");}},[]);
 useEffect(()=>{if(!open)return;void refresh();const id=setInterval(()=>{if(!document.hidden)void refresh();},3000);return()=>clearInterval(id);},[refresh,open]);
 useEffect(()=>{if(messages.length>oldCount.current){bottom.current?.scrollIntoView({block:"nearest",behavior:"smooth"});oldCount.current=messages.length;}},[messages.length]);
 async function send(e:React.FormEvent){e.preventDefault();if(!body.trim()||sending)return;setSending(true);try{const response=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error);setBody("");await refresh();}catch(e){toast.error(e instanceof Error?e.message:"Your message was not sent.");}finally{setSending(false);}}
 return <aside id="lucky-lounge" className="chat-panel" hidden={!open}><div className="chat-header"><h2><MessageCircle size={17}/>The lucky lounge</h2><div className="chat-header-actions"><span className="chat-live"><span className="live-dot"/>{error?"RETRYING":"LIVE"}</span><button className="icon-button" aria-label="Close lounge" onClick={onClose}><X size={14}/></button></div></div><div className="chat-pinned"><span className="pin-icon"><Sparkles size={16}/></span><p>Good vibes. Big possibilities.<span>Say hello while the next round rolls in.</span></p></div><div className="chat-messages" role="log" aria-label="Lounge messages" aria-live="polite"><div className="chat-date">THE LOUNGE IS OPEN</div>{error?<div className="chat-error"><p>{error}</p><button onClick={refresh}>Reconnect<RefreshCw size={12}/></button></div>:!ready?<div className="system-message">Connecting to the lounge…</div>:messages.length===0?<div className="system-message"><Clover size={18}/><strong>First here? Lucky you.</strong><p>Start the conversation. Messages appear here for everyone in the room.</p></div>:messages.map(message=><div key={message.id} className={`chat-message ${message.nickname===nickname?"my-message":""}`}><Avatar index={parseInt(message.nickname.slice(-4),16)%8} small/><div><div className="message-author"><strong>{message.nickname}</strong>{message.nickname===nickname&&<span>YOU</span>}<time>{new Date(message.createdAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time></div><p>{message.body}</p></div></div>)}<div ref={bottom}/></div><form className="chat-composer" onSubmit={send}><div className="chat-input"><input value={body} onChange={e=>setBody(e.target.value)} aria-label="Chat message" placeholder="Send some good luck…" maxLength={280}/><button disabled={sending||!body.trim()||!ready} type="submit" aria-label="Send message"><Send size={16}/></button></div><span><ShieldCheck size={11}/>{body.length>240?`${body.length}/280 characters`:"Keep it kind. Never share your seed phrase."}</span></form><div className="chat-bottom"><Clover size={14}/><span>{nickname?`Chatting as ${nickname}`:"A little community. A little luck."}</span></div></aside>;
}

export function Reel({result,onFinish,sound,phase,setPhase}:{result:DrawResult|null;onFinish:()=>void;sound:boolean;phase:string;setPhase:(phase:string)=>void}){
 const track=useRef<HTMLDivElement>(null);const viewport=useRef<HTMLDivElement>(null);const audio=useRef<AudioContext|null>(null);const soundRef=useRef(sound);const finishRef=useRef(onFinish);const [settled,setSettled]=useState(false);
 useEffect(()=>{soundRef.current=sound;if(sound&&!audio.current)audio.current=new AudioContext();if(sound)void audio.current?.resume();},[sound]);
 useEffect(()=>{finishRef.current=onFinish;},[onFinish]);
 useEffect(()=>{if(!result||!track.current||!viewport.current)return;setSettled(false);setPhase("rolling");let frame=0;let done=false;const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const el=track.current;const width=(el.firstElementChild as HTMLElement).offsetWidth;const end=viewport.current.clientWidth/2-(48*(width+10)+width/2);const duration=reduced?300:8500;let lastIndex=-1;
 const beep=(frequency:number,length=.022,volume=.025)=>{const context=audio.current;if(!soundRef.current||!context||context.state!=="running")return;const oscillator=context.createOscillator();const gain=context.createGain();oscillator.type="sine";oscillator.frequency.value=frequency;gain.gain.setValueAtTime(volume,context.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+length);oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+length);};
 const animation=el.animate([{transform:"translateX(-40px)",filter:"blur(0px)",offset:0},{filter:"blur(1.5px)",offset:.14},{filter:"blur(0px)",offset:.72},{transform:`translateX(${end}px)`,filter:"blur(0px)",offset:1}],{duration,easing:"cubic-bezier(.1,.65,.08,1)",fill:"forwards"});
 const tick=()=>{if(done)return;const t=Number(animation.currentTime??0)/duration;const x=new DOMMatrix(getComputedStyle(el).transform).m41;const index=Math.floor(-x/(width+10));if(index!==lastIndex){beep(490+t*480);lastIndex=index;}if(t>.68)setPhase("slowing");frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);
 animation.onfinish=()=>{done=true;cancelAnimationFrame(frame);setSettled(true);setPhase("winner");[523,659,784,1047].forEach((f,i)=>setTimeout(()=>beep(f,.23,.045),i*110));finishRef.current();};
 return()=>{done=true;cancelAnimationFrame(frame);animation.cancel();};
 },[result,setPhase]);
 useEffect(()=>()=>{void audio.current?.close();},[]);
 const items=Array.from({length:result?56:16},(_,i)=>i===48&&result?result.index:i%8);
 return <div ref={viewport} className={`reel-window ${phase} ${settled?"settled":""}`}><div className="reel-pointer"><span/><i/></div><div className="reel-track" ref={track}>{items.map((index,i)=><div className={`ticket ${settled&&i===48?"winning-ticket":""}`} key={i}><Avatar index={index}/><strong>{DEMO_WALLETS[index]}</strong><span>{settled&&i===48?"LUCKY WINNER":"LUCKY HOLDER"}</span></div>)}</div>{settled&&<div className="reel-flash"/>}</div>;
}

export function Winner({result,open,setOpen,demoWallet,seconds}:{result:DrawResult|null;open:boolean;setOpen:(v:boolean)=>void;demoWallet:boolean;seconds:number}){
 const outcome=demoViewerOutcome(result?.index??-1,demoWallet,[0,2,5]);
 const won=outcome==="winner",lost=outcome==="miss";
 const title=won?"You're the lucky one!":lost?"Better luck next time.":"Luck found a wallet.";
 return <Dialog open={open} onOpenChange={setOpen}><DialogContent className={`lucky-dialog winner-dialog outcome-${outcome}`}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{won?"Your demo wallet won this round.":lost?"Your wallet wasn't selected this round.":"Watch the draw. Meet the lucky winner."}</DialogDescription></DialogHeader>{result&&<>
 {won&&<div className="confetti" aria-hidden="true">{Array.from({length:32},(_,i)=><i key={i} style={{left:`${i*3.2}%`,background:i%3===0?"#b8a4f7":i%3===1?"#7eb8ff":"#ffffff",animationDelay:`${i%7*.13}s`,transform:`rotate(${i*23}deg)`}}/>)}</div>}
 {lost?<div className="next-chance-art"><Clover size={38}/><span><Clock3 size={15}/></span></div>:<div className="winner-medallion"><div/><Avatar index={result.index}/><span><Clover size={17}/></span></div>}
 {lost?<><p className="loss-copy">A fresh round. A fresh chance.<br/>Keep holding — your next lucky moment could be close.</p><div className="round-winner-summary"><Avatar index={result.index} small/><div><span>THIS ROUND'S WINNER</span><strong>{result.wallet}</strong></div><b>{result.amount.toFixed(3)}<span>SOL</span></b></div></>:<><span className="result-wallet-label">{won?"YOUR WINNING WALLET":"WINNING WALLET"}</span><strong className="winner-wallet">{result.wallet}</strong><div className="winner-amount">{won?"+":""}{result.amount.toFixed(3)}<span>SOL</span></div><p className="winner-detail">{won?"One wallet. Your lucky moment.":"One wallet. One lucky moment."}</p></>}
 <div className="result-countdown"><span>NEXT DRAW IN</span><strong>{String(Math.floor(seconds/60)).padStart(2,"0")}<i>:</i>{String(seconds%60).padStart(2,"0")}</strong></div>
 <div className="notice">Demo round #{result.round} · No SOL was sent.{!demoWallet&&<><br/>Connect the demo wallet to see your personal result.</>}</div><button className="btn primary" onClick={()=>setOpen(false)}>{won?"Let's go again":lost?"I'm in for the next one":"Back to the draw"}<ArrowRight size={15}/></button>
 </>}</DialogContent></Dialog>;
}
