"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {ArrowRight,ArrowUpRight,Check,Clover,Clock3,Info,MessageCircle,Play,ShieldCheck,Users,Volume2,VolumeX,Wallet,Zap} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Toaster} from "sonner";
import {Avatar,Chat,Reel,Solana,Winner,short,useDraw} from "./experience";
import {WalletDialog,WalletPanel,useWallet} from './wallets';
import {demoResult,DrawResult,ROUND_MS} from "@/lib/draw";

export default function Home(){
 const {state,seconds,online}=useDraw();const wallet=useWallet();
 const [chatOpen,setChatOpen]=useState(false);
 const [sound,setSound]=useState(false),[info,setInfo]=useState(false),[phase,setPhase]=useState("idle"),[result,setResult]=useState<DrawResult|null>(null),[winnerOpen,setWinnerOpen]=useState(false);
 const lastRound=useRef<number|null>(null);const busy=phase==="rolling"||phase==="slowing";
 const preview=useCallback(()=>{if(busy)return;setWinnerOpen(false);setResult({...demoResult(state?.round??Math.floor(Date.now()/ROUND_MS))});},[busy,state?.round]);
 useEffect(()=>{if(!state)return;if(lastRound.current===null){lastRound.current=state.round;return;}if(state.round!==lastRound.current){lastRound.current=state.round;if(!busy){setWinnerOpen(false);setResult(state.history[0]);}}},[state,busy]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"preview_lucky_reveal",title:"Preview the lucky draw",description:"Play the simulated wallet winner reveal. No wallet connection, transaction, payout, or change to the scheduled round.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=="object"||Array.isArray(input)||Object.keys(input).length)throw new Error("Expected an empty object");if(busy)throw new Error("A reveal is already playing");preview();await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {started:true,simulated:true};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[preview,busy]);
 const displayRound=state?.round.toString()??"—";const pool=busy&&result?result.amount:state?.pool??12.482;
 const status=phase==="rolling"?"The wallets are rolling. Here we go…":phase==="slowing"?"Slowing down. Who’s feeling lucky?":phase==="winner"&&result?`${result.wallet} is the lucky wallet. Next round is open.`:"Waiting for the next lucky wallet";
 return <><Toaster theme="dark" position="bottom-center"/><div className="app-shell"><header className="topbar"><a className="brand" href="/" aria-label="Lucky home"><span className="brand-symbol"><Clover size={26} strokeWidth={2.4}/></span>lucky<span className="brand-dot">.</span></a><nav><a className="nav-active" href="#draw">Draw room<span className="live-dot"/></a><button onClick={()=>setInfo(true)}>How it works<ArrowUpRight size={13}/></button></nav><div className="header-actions"><span className="network"><Solana size={13}/>Solana</span><button className="btn primary" onClick={()=>wallet.setOpen(true)}><Wallet size={16}/>{wallet.demo?"Demo wallets":wallet.rows.length?`${wallet.rows.length} wallets`:wallet.address?short(wallet.address):"Connect wallet"}</button><button className={`chat-toggle ${chatOpen?"active":""}`} onClick={()=>setChatOpen(v=>!v)} aria-label={chatOpen?"Close chat":"Open chat"} aria-expanded={chatOpen} aria-controls="lucky-lounge"><MessageCircle size={18}/></button></div></header>
 <div className="page-heading"><div><div className="eyebrow"><span className="live-dot"/>THE HOLDER’S DRAW</div><h1>A little luck. A lot of possibility<span>.</span></h1></div><button className="demo-badge" aria-label="About this interactive demo" onClick={()=>setInfo(true)}><span/>Interactive demo<Info size={13}/></button></div>
 <div className={`dashboard ${chatOpen?"chat-open":"chat-closed"}`}><main id="draw"><section className={`draw-panel phase-${phase}`}><div className="draw-top"><span className="round-label"><i/>ROUND #{displayRound}</span><span className="round-frequency"><Clock3 size={13}/>Every 3 minutes</span></div><div className="prize"><div className="eyebrow">CURRENT DEMO PRIZE POOL</div><div className="prize-amount"><span className="sol-coin"><Solana size={28}/></span>{pool.toFixed(3)}<span>SOL</span></div><p>Collected fees. One lucky holder.</p><span className="pool-tag"><Zap size={12}/>Simulated fee accumulation</span></div><div className="reel-heading"><span role="status"><span className="live-dot"/>{status}</span><button className="icon-button" aria-label={sound?"Mute draw sounds":"Enable draw sounds"} aria-pressed={sound} onClick={()=>setSound(!sound)}>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>}</button></div>
 <Reel result={result} phase={phase} setPhase={setPhase} sound={sound} onFinish={()=>setWinnerOpen(true)}/>
 <div className="countdown-row"><div><span className="eyebrow">NEXT DRAW IN</span><div className={`countdown ${seconds<=10?"closing":""}`}>{String(Math.floor(seconds/60)).padStart(2,"0")}<span>:</span>{String(seconds%60).padStart(2,"0")}</div></div><div className="countdown-copy"><span className="next-label">{seconds<=10?"The next reveal is about to begin…":"Your next three minutes could hit different."}</span><div className="time-track" role="progressbar" aria-label="Time until next draw" aria-valuemin={0} aria-valuemax={180} aria-valuenow={seconds}><i style={{width:`${seconds/180*100}%`}}/></div><span className="time-caption">{online?"Holding is your entry. More tokens, more chances.":"Reconnecting to the clock. Showing local demo time."}</span></div></div><div className="draw-footer"><button onClick={()=>setInfo(true)} className="fairness-button"><ShieldCheck size={14}/>Weighted by token holdings</button><button onClick={preview} disabled={busy}>{busy?"Finding a lucky wallet…":"Preview the reveal"}<Play size={12} fill="currentColor"/></button></div></section>
 <section className="stats-strip"><div><span><Users size={14}/>Current participants</span><strong>8<span>wallets</span></strong></div><div><span><Solana size={14}/>Total winnings sent</span><strong>0.000<span>SOL</span></strong></div><div><span><Clock3 size={14}/>Draw interval</span><strong>3<span>minutes</span></strong></div></section>
 <div className="lower-grid"><WalletPanel wallet={wallet}/><section className="history-panel panel"><div className="section-heading"><h2>Recent draws<span>DEMO</span></h2><span className="live-dot"/></div>{state?.history.map(item=><button key={item.round} className="history-row" onClick={()=>{if(!busy){setResult(item);setWinnerOpen(false);}}} disabled={busy} aria-label={`Replay demo draw ${item.round}`}><Avatar index={item.index} small/><div><strong>{item.wallet}</strong><span>{Math.max(0,Math.floor((state.serverTime-item.at)/60000))} min ago · #{item.round}</span></div><div className="history-amount">{item.amount.toFixed(3)}<span>SOL</span></div><Play size={11} className="history-check"/></button>)}<button className="history-more" onClick={()=>setInfo(true)}>How are winners selected?<ArrowUpRight size={13}/></button></section></div>
 <section className="steps"><div><span>01</span><p>Hold the token<strong>Your balance is your entry.</strong></p></div><ArrowRight size={15}/><div><span>02</span><p>Watch the draw<strong>A fresh chance every 3 minutes.</strong></p></div><ArrowRight size={15}/><div><span>03</span><p>Catch a little luck<strong>One winner takes the SOL pool.</strong></p></div></section></main><Chat open={chatOpen} onClose={()=>setChatOpen(false)}/></div>
 <footer className="site-footer"><span className="footer-brand"><Clover size={15}/>lucky.</span><span>Built for the holders.</span><p>Demo rounds & sample balances · No real funds are distributed</p><span><Solana size={12}/>On Solana</span></footer></div>
 <Dialog open={info} onOpenChange={setInfo}><DialogContent className="lucky-dialog"><DialogHeader><DialogTitle>Every token is a chance.</DialogTitle><DialogDescription>The more eligible tokens you hold, the greater your share of the draw.</DialogDescription></DialogHeader><div className="how-step"><span>01</span><div><strong>Your tokens stay with you</strong><p>Phantom connects your public address so the app can read your holdings. Connecting is never a token transfer.</p></div></div><div className="how-step"><span>02</span><div><strong>A weighted draw every 3 minutes</strong><p>Holding 1% of eligible tokens gives a 1% chance in each draw. Eligible holdings are separate from total token supply.</p></div></div><div className="how-step"><span>03</span><div><strong>The fee pool goes to the winner</strong><p>A live launch needs a holder snapshot, verifiable randomness, and a funded payout program. The reel displays the chosen result.</p></div></div><div className="notice">This framework uses eight sample wallets and reproducible demo results. Prize pools and payouts are simulated. The chat is shared; Phantom balances are real only when the token is configured.</div></DialogContent></Dialog><WalletDialog wallet={wallet}/><Winner result={result} open={winnerOpen} setOpen={setWinnerOpen} demoWallet={wallet.demo} seconds={seconds}/></>;
}


