"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,Copy,Plus,RefreshCw,ShieldCheck,Sparkles,Wallet,X} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import {formatUnits} from '@/lib/solana';
import {DEMO_WALLETS} from '@/lib/draw';

type Provider={isPhantom:boolean;publicKey?:{toString():string};connect:(options?:{onlyIfTrusted:boolean})=>Promise<{publicKey:{toString():string}}>;disconnect:()=>Promise<void>;signMessage:(message:Uint8Array,encoding:'utf8')=>Promise<{signature:Uint8Array}>;on:(event:string,fn:(key?:{toString():string}|null)=>void)=>void;removeListener:(event:string,fn:(key?:{toString():string}|null)=>void)=>void};
const provider=()=>typeof window==='undefined'?undefined:(window as unknown as {phantom?:{solana?:Provider}}).phantom?.solana;
const short=(address:string)=>address.length>14?`${address.slice(0,4)}…${address.slice(-4)}`:address;
const amount=(value?:string)=>{if(value===undefined)return '—';const [whole,fraction]=value.split('.');return `${whole.replace(/\B(?=(\d{3})+(?!\d))/g,',')}${fraction?'.'+fraction.slice(0,4):''}`;};
type Holding={configured:boolean;amount?:string;rawAmount?:string;decimals?:number;supplyRaw?:string;symbol?:string;supplyShare?:number;solBalance?:string;error?:string};
type LinkedWallet={address:string;createdAt:number};
const DEMO_ROWS=[{address:DEMO_WALLETS[0],createdAt:0},{address:DEMO_WALLETS[2],createdAt:1},{address:DEMO_WALLETS[5],createdAt:2}];
const DEMO_HOLDINGS:Record<string,Holding>={
 [DEMO_WALLETS[0]]:{configured:true,amount:'125000',rawAmount:'125000000000',decimals:6,supplyRaw:'100000000000000',supplyShare:.125,symbol:'LUCKY',solBalance:'3.2841'},
 [DEMO_WALLETS[2]]:{configured:true,amount:'500000',rawAmount:'500000000000',decimals:6,supplyRaw:'100000000000000',supplyShare:.5,symbol:'LUCKY',solBalance:'12.0916'},
 [DEMO_WALLETS[5]]:{configured:true,amount:'300000',rawAmount:'300000000000',decimals:6,supplyRaw:'100000000000000',supplyShare:.3,symbol:'LUCKY',solBalance:'1.7283'},
};
export function useWallet(){
 const [address,setAddress]=useState(''),[demo,setDemo]=useState(false),[linked,setLinked]=useState<LinkedWallet[]>([]),[holdings,setHoldings]=useState<Record<string,Holding>>({}),[busy,setBusy]=useState(false),[connecting,setConnecting]=useState(false),[missing,setMissing]=useState(false),[open,setOpen]=useState(false),[error,setError]=useState(''),[stage,setStage]=useState('');
 const sequence=useRef(0),abort=useRef<AbortController|null>(null),linkedRef=useRef(linked);linkedRef.current=linked;
 const refresh=useCallback(async()=>{
  abort.current?.abort();const controller=new AbortController();abort.current=controller;const seq=++sequence.current;setBusy(true);setError('');
  try{const response=await fetch('/api/wallets',{signal:controller.signal});const data=await response.json() as {wallets?:LinkedWallet[];error?:string};if(!response.ok||!data.wallets)throw new Error(data.error??'Could not load your wallets.');if(seq!==sequence.current)return;setLinked(data.wallets);setHoldings({});
   for(let i=0;i<data.wallets.length;i+=4){await Promise.all(data.wallets.slice(i,i+4).map(async row=>{try{const res=await fetch(`/api/holdings?wallet=${encodeURIComponent(row.address)}`,{signal:controller.signal});const balance=await res.json() as Holding;if(seq===sequence.current&&!controller.signal.aborted)setHoldings(old=>({...old,[row.address]:balance}));}catch{if(!controller.signal.aborted)setHoldings(old=>({...old,[row.address]:{configured:false,error:'Balance unavailable. Refresh to retry.'}}));}}));}
  }catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Could not load your wallets.');}finally{if(seq===sequence.current&&!controller.signal.aborted)setBusy(false);}
 },[]);
 useEffect(()=>{void refresh();return()=>{abort.current?.abort();};},[refresh]);
 useEffect(()=>{const id=setInterval(()=>{if(!document.hidden&&!demo&&!connecting)void refresh();},60000);return()=>clearInterval(id);},[refresh,demo,connecting]);
 useEffect(()=>{const p=provider();if(!p?.isPhantom)return;const changed=(key?:{toString():string}|null)=>{setAddress(key?.toString()??'');setDemo(false);};const disconnected=()=>setAddress('');p.on('accountChanged',changed);p.on('disconnect',disconnected);void p.connect({onlyIfTrusted:true}).then(r=>setAddress(r.publicKey.toString())).catch(()=>{});return()=>{p.removeListener('accountChanged',changed);p.removeListener('disconnect',disconnected);};},[]);
 async function connect(){const p=provider();setMissing(!p?.isPhantom);if(!p?.isPhantom)return;setConnecting(true);setStage('Approve connection in Phantom…');setError('');
  try{const connected=await p.connect();const current=connected.publicKey.toString();setAddress(current);setDemo(false);if(linkedRef.current.some(row=>row.address===current)){toast('This wallet is already linked. Switch accounts in Phantom to add another.');await refresh();return;}
   setStage('Preparing wallet verification…');const response=await fetch('/api/wallets/challenge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address:current})});const challenge=await response.json() as {challengeId:string;message:string;error?:string};if(!response.ok)throw new Error(challenge.error??'Could not verify this wallet.');
   setStage('Sign the ownership message in Phantom…');const signed=await p.signMessage(new TextEncoder().encode(challenge.message),'utf8');const signature=btoa(String.fromCharCode(...signed.signature));
   setStage('Saving your verified wallet…');const verified=await fetch('/api/wallets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address:current,challengeId:challenge.challengeId,signature})});const result=await verified.json() as {error?:string};if(!verified.ok)throw new Error(result.error??'Could not link your wallet.');await refresh();setOpen(false);toast.success('Wallet linked. All your holdings are in Your position.');
  }catch(e){const message=(e as {code?:number}).code===4001?'Cancelled in Phantom. Nothing was transferred.':e instanceof Error?e.message:'Could not link your wallet. Please try again.';setError(message);toast.error(message);}finally{setConnecting(false);setStage('');}
 }
 async function disconnect(){try{if(!demo)await provider()?.disconnect();setDemo(false);setAddress('');toast('Phantom disconnected. Your verified wallet list is saved.');}catch{toast.error('Disconnect failed. Try again in Phantom.');}}
 async function unlink(wallet:string){try{const response=await fetch(`/api/wallets?address=${encodeURIComponent(wallet)}`,{method:'DELETE'});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error);await refresh();toast('Wallet removed from your position.');}catch(e){toast.error(e instanceof Error?e.message:'Could not remove this wallet.');}}
 function explore(){setDemo(true);setOpen(false);toast('Showing three sample wallets. No real funds.');}
 const rows=demo?DEMO_ROWS:linked;const balances=demo?DEMO_HOLDINGS:holdings;const complete=rows.length>0&&rows.every(row=>balances[row.address]?.configured&&balances[row.address]?.rawAmount!==undefined&&!balances[row.address]?.error);
 const reference=balances[rows[0]?.address];const totalRaw=complete?rows.reduce((sum,row)=>sum+BigInt(balances[row.address].rawAmount!),0n):null;
 const total=totalRaw!==null?formatUnits(totalRaw,reference?.decimals??0):undefined;const supply=reference?.supplyRaw?BigInt(reference.supplyRaw):0n;const share=totalRaw!==null&&supply>0n?Number(totalRaw*1000000n/supply)/10000:undefined;
 return {address,demo,rows,balances,total,share,symbol:reference?.symbol??'LUCKY',busy:!demo&&busy,connecting,stage,missing,open,setOpen,error:demo?'':error,connect,disconnect,unlink,explore,refresh,exitDemo:()=>setDemo(false)};
}
type WalletState=ReturnType<typeof useWallet>;
export function WalletPanel({wallet}:{wallet:WalletState}){return <section className="position-panel panel multi-position"><div className="section-heading"><h2>Your position{wallet.demo&&<span>DEMO</span>}</h2><div className="position-tools"><button className="icon-button" aria-label="Refresh all wallet holdings" disabled={wallet.busy} onClick={()=>wallet.refresh()}><RefreshCw size={14} className={wallet.busy?'spin':''}/></button><button className="icon-button" aria-label="Manage linked wallets" onClick={()=>wallet.setOpen(true)}><Plus size={16}/></button></div></div>{wallet.rows.length>0?<><div className="portfolio-total"><span>COMBINED TOKEN HOLDINGS</span><strong>{wallet.busy&&!wallet.total?'…':amount(wallet.total)}<small>{wallet.symbol}</small></strong><div><span>{wallet.rows.length} linked wallets</span><span>{wallet.share!==undefined?`${wallet.share.toFixed(3)}% of supply`:'Token balance unavailable'}</span></div></div><div className="wallet-list">{wallet.rows.map((row,index)=>{const h=wallet.balances[row.address];return <div className="portfolio-wallet" key={row.address}><span className="portfolio-icon"><Wallet size={15}/></span><div className="portfolio-address"><strong title={row.address}>{short(row.address)}</strong><span>{wallet.demo?'Demo':row.address===wallet.address?'Active in Phantom':'Verified wallet'}{!wallet.demo&&<Check size={9}/>}</span></div><div className="portfolio-balance"><strong title={h?.amount}>{h?.error?'Retry needed':!h?'Loading…':h.configured?amount(h.amount):'Token not set'}{h?.configured&&<small>{wallet.symbol}</small>}</strong><span>{h?.solBalance!==undefined?`${amount(h.solBalance)} SOL`:h?.error?'Could not read balance':'— SOL'}</span></div></div>;})}</div><div className="portfolio-odds"><span>Combined draw probability</span><strong>{wallet.demo?'18.50%':'Pending eligibility snapshot'}</strong></div><div className="position-bottom"><button onClick={()=>wallet.setOpen(true)} className="text-button"><Plus size={12}/>Link another wallet</button>{wallet.demo&&<button className="text-button" onClick={wallet.exitDemo}>Exit demo</button>}</div><span className="tiny-note">{wallet.demo?'Sample portfolio · 925,000 of 5,000,000 eligible tokens.':'Every wallet is counted once. Payouts go to the winning wallet.'}</span></>:<><div className="connect-illustration"><Wallet size={26}/><i><Plus size={13}/></i></div><h3>All your wallets. One position.</h3><p>Link your Phantom accounts to see each balance<br/>and your combined token holdings.</p><button className="btn subtle" onClick={()=>wallet.setOpen(true)}>Link wallets<ArrowRight size={15}/></button><span className="tiny-note">Your tokens stay in your wallets.</span></>}{wallet.error&&<div className="portfolio-error" role="alert">{wallet.error}<button onClick={()=>wallet.refresh()}>Retry</button></div>}</section>;}
export function WalletDialog({wallet}:{wallet:WalletState}){return <Dialog open={wallet.open} onOpenChange={value=>{if(!wallet.connecting)wallet.setOpen(value);}}><DialogContent className="lucky-dialog wallet-manager"><DialogHeader><DialogTitle>Your wallets. Together.</DialogTitle><DialogDescription>Link each account once to see all your holdings under Your position.</DialogDescription></DialogHeader><div className="link-instructions"><span>1</span><p>Select an account in Phantom.</p><span>2</span><p>Connect and sign the ownership message.</p><span>3</span><p>Switch accounts in Phantom and repeat.</p></div>{wallet.address&&!wallet.demo&&<div className="active-wallet-line"><span className="live-dot"/>Selected in Phantom: {short(wallet.address)}</div>}<button className="btn phantom-btn" disabled={wallet.connecting} onClick={wallet.connect}><span className="phantom-mark">••</span>{wallet.connecting?'Waiting for Phantom…':wallet.rows.length&&!wallet.demo?'Link another Phantom wallet':'Connect & link Phantom'}<ArrowRight size={17}/></button>{wallet.stage&&<div className="link-stage" role="status"><RefreshCw size={13} className="spin"/>{wallet.stage}</div>}{wallet.missing&&<div className="notice" role="status">Phantom isn't available in this browser. Open this page in a browser with the Phantom extension, or in Phantom's mobile browser.<a href="https://phantom.com/download" target="_blank" rel="noreferrer">Get Phantom<ArrowRight size={12}/></a></div>}{wallet.error&&<p className="wallet-error" role="alert">{wallet.error}</p>}{!wallet.demo&&wallet.rows.length>0&&<div className="linked-manage-list">{wallet.rows.map(row=><div key={row.address}><span title={row.address}><ShieldCheck size={12}/>{short(row.address)}</span><button className="icon-button" onClick={()=>wallet.unlink(row.address)} disabled={wallet.connecting} aria-label={`Unlink ${short(row.address)}`}><X size={13}/></button></div>)}</div>}<button className="btn subtle" disabled={wallet.connecting} onClick={wallet.explore}>Explore demo wallets<Sparkles size={15}/></button>{(wallet.address||wallet.demo)&&<button className="text-button" disabled={wallet.connecting} onClick={wallet.disconnect}>{wallet.demo?'Exit demo wallets':'Disconnect active Phantom wallet'}</button>}<p className="tiny-note">Signing proves ownership. It does not transfer funds.<br/>Linked wallets are saved to your private position.</p></DialogContent></Dialog>;}
